### ISSUE TITLE
请问以下工作单元是做什么用的？包裹在里面的是事务么？

### ISSUE THREAD

**Issue by zfeihong** [zdz72113/NETCore_BasicKnowledge.Examples#1]
using (var uow = _uowFactory.Create())
{
     await _productRepository.AddAsync(prod);
     uow.SaveChanges();
 }

**Comment by zdz72113** [comment]
> 
> 
> using (var uow = _uowFactory.Create())
> {
> await _productRepository.AddAsync(prod);
> uow.SaveChanges();
> }

是的
